#!/usr/bin/bash
#
# Put customizations to your image in this file.

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Munin plugins
MUNIN_PLUGIN_SRC='/opt/local/lib/munin/plugins'
MUNIN_PLUGIN_DST='/opt/local/etc/munin/plugins'
MUNIN_PLUGINS=(
	'nginx_request'
	'nginx_status'
)

# Exit if any commands fail
set -o errexit

# Nginx SSL folder
echo "* Create ssl folder"
mkdir -p /opt/local/etc/nginx/ssl

# Setup gunicorn
echo "* Setup gunicorn"
mkdir -p /opt/local/etc/gunicorn
svccfg import /tmp/gunicorn.xml

# Activate munin plugins
echo "* Activate munin plugins"
for plugin in "${MUNIN_PLUGINS[@]}"; do
	if [ ! -x ${MUNIN_PLUGIN_SRC}/${plugin} ]; then
		plugin_src=${plugin%_*}_
		[ ! -x ${MUNIN_PLUGIN_SRC}/${plugin_src} ] && \
			plugin_src=${plugin_src%%_*}_
	else
		plugin_src=${plugin}
	fi
	if [[ -x ${MUNIN_PLUGIN_SRC}/${plugin_src} ]]; then
		echo "  ${plugin}"
		ln -sf ${MUNIN_PLUGIN_SRC}/${plugin_src} ${MUNIN_PLUGIN_DST}/${plugin}
	fi
done

# Clean up
echo "* Cleaning up."
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y
