#!/usr/bin/bash
#
# Put customizations to your image in this file.

NETMGT_VERSION='0.0.11'

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Munin plugins
MUNIN_PLUGINS="
	nginx_request
	nginx_status
"

# Exit if any commands fail
set -o errexit

echo "* Use default python 3.7"
pkg_alternatives manual python37

echo "* Create ssl folder"
mkdir -p /opt/local/etc/nginx/ssl

echo "* Download and extract netmgt to /opt/netmgt"
mkdir -p /opt/netmgt
curl -L "https://github.com/wiedi/django-netmgt/archive/v${NETMGT_VERSION}.tar.gz" | gtar xz -C /opt/netmgt --strip-components=1

echo "* Setup permissions for netmgt folder"
chown -R www:www /opt/netmgt

echo "* Install missing dependencies via pip"
pip3.7 install -r /opt/netmgt/req.txt

echo "* Copy default (basic) netmgt settings"
cp /tmp/netmgt-settings.py /opt/netmgt/netmgt_web/settings.py
rm /tmp/netmgt-settings.py

echo "* Setup gunicorn"
mkdir -p /opt/local/etc/gunicorn
svccfg import /tmp/gunicorn.xml

echo "* Activate munin plugins"
/opt/core/bin/munin-node-plugins ${MUNIN_PLUGINS}

echo "* Cleanup home/admin because of delegate dataset usage"
rm -rf /home/admin/.[^.]*

echo "* Cleaning up."
rm -rf /root/*
sm-prepare-image -y
